theme: jekyll-theme-cayman
title: Warren's Intro to IT Assignment 1
description: This site was established for my RMIT assignment
pages:
  markdown:
    extras: true
include:
  - section1.md
  - section2.md
  - section4.md
  - section4.md
  - fulljob.md